layout_spectrum: 0.9033631
color:
  saturation: 0.8817204
  lightness: 0.09318996
  brandStrength: 0.9884138
  brandColors:
    - '#E7E9E8'
    - '#8F9292'
    - '#F00000'
    - '#576473'
    - '#200B01'
  rhythmicContrast: 0.6810036
typography_spectrum: 0.9014337
name: Rob Bates Photography
